import pygame, random, time


pygame.init()

display_height = 800
display_width = int(display_height * 1.77777778)
scherm = pygame.display.set_mode((display_width, display_height))
clock = pygame.time.Clock()
white = (205,205,205)
intro = True

def text_objects(text, font):
    textSurface = font.render(text, True, white)
    return textSurface, textSurface.get_rect()

def button(msg,x,y,w,h,ic,ac,action=None):
    mouse = pygame.mouse.get_pos()
    click = pygame.mouse.get_pressed()
    if x+w > mouse[0] > x and y+h > mouse[1] > y:
        pygame.draw.rect(scherm, ac,(x,y,w,h))

        #Code is niet functioneel maar met de hulp van jullie zullen we dit functioneel maken.
        if click[0] == 1 and action == "opt1":
            #Foute antwoord
        elif click[0] == 1 and action == "opt2":
            #Goede antwoord

    else:
        pygame.draw.rect(scherm, ic,(x,y,w,h))

    smallText = pygame.font.Font("pixel.ttf",25)
    textSurf, textRect = text_objects(msg, smallText)
    textRect.center = ( (x+(w/2)), (y+(h/2)) )
    scherm.blit(textSurf, textRect)

def imagesq():
    qbuttonwidth = display_height / 1.5
    qbuttonheight = 60
    qbuttonposx = ((display_width / 2) - (qbuttonwidth / 2))
    qbutton1ypos = display_height - (qbuttonheight * 2)
    qbutton2ypos = display_height - (qbuttonheight * 3.5)
    qbutton3ypos = display_height - (qbuttonheight * 5)
    qred = (255, 102, 102)
    qblue = (102, 178, 255)
    qyellow = (255, 255, 102)
    qgreen = (102, 255, 102)

    eq1 = pygame.image.load('entertainment1.png')
    eq2 = pygame.image.load('entertainment2.png')
    eq3 = pygame.image.load('entertainment3.png')
    eq4 = pygame.image.load('entertainment4.png')
    eq5 = pygame.image.load('entertainment5.png')
    eq6 = pygame.image.load('entertainment6.png')
    eq7 = pygame.image.load('entertainment7.png')
    eq8 = pygame.image.load('entertainment8.png')
    eq9 = pygame.image.load('entertainment9.png')
    eq10 = pygame.image.load('entertainment10.png')
    eq11 = pygame.image.load('entertainment11.png')
    eq12 = pygame.image.load('entertainment12.png')
    eq13 = pygame.image.load('entertainment13.png')
    eq14 = pygame.image.load('entertainment14.png')
    eq15 = pygame.image.load('entertainment15.png')
    eq16 = pygame.image.load('entertainment16.png')
    eq17 = pygame.image.load('entertainment17.png')
    eq18 = pygame.image.load('entertainment18.png')
    eq19 = pygame.image.load('entertainment19.png')
    eq20 = pygame.image.load('entertainment20.png')
    eq21 = pygame.image.load('entertainment21.png')
    eq22 = pygame.image.load('entertainment22.png')
    eq23 = pygame.image.load('entertainment23.png')
    eq24 = pygame.image.load('entertainment24.png')
    gq1 = pygame.image.load('geografie1.png')
    gq2 = pygame.image.load('geografie2.png')
    gq3 = pygame.image.load('geografie3.png')
    gq4 = pygame.image.load('geografie4.png')
    gq5 = pygame.image.load('geografie5.png')
    gq6 = pygame.image.load('geografie6.png')
    gq7 = pygame.image.load('geografie7.png')
    gq8 = pygame.image.load('geografie8.png')
    gq9 = pygame.image.load('geografie9.png')
    gq10 = pygame.image.load('geografie10.png')
    gq11 = pygame.image.load('geografie11.png')
    gq12 = pygame.image.load('geografie12.png')
    gq13 = pygame.image.load('geografie13.png')
    gq14 = pygame.image.load('geografie14.png')
    gq15 = pygame.image.load('geografie15.png')
    gq16 = pygame.image.load('geografie16.png')
    gq17 = pygame.image.load('geografie17.png')
    gq18 = pygame.image.load('geografie18.png')
    gq19 = pygame.image.load('geografie19.png')
    gq20 = pygame.image.load('geografie20.png')
    gq21 = pygame.image.load('geografie21.png')
    gq22 = pygame.image.load('geografie22.png')
    gq23 = pygame.image.load('geografie23.png')
    gq24 = pygame.image.load('geografie24.png')
    hq1 = pygame.image.load('historie1.png')
    hq2 = pygame.image.load('historie2.png')
    hq3 = pygame.image.load('historie3.png')
    hq4 = pygame.image.load('historie4.png')
    hq5 = pygame.image.load('historie5.png')
    hq6 = pygame.image.load('historie6.png')
    hq7 = pygame.image.load('historie7.png')
    hq8 = pygame.image.load('historie8.png')
    hq9 = pygame.image.load('historie9.png')
    hq10 = pygame.image.load('historie10.png')
    hq11 = pygame.image.load('historie11.png')
    hq12 = pygame.image.load('historie12.png')
    hq13 = pygame.image.load('historie13.png')
    hq14 = pygame.image.load('historie14.png')
    hq15 = pygame.image.load('historie15.png')
    hq16 = pygame.image.load('historie16.png')
    hq17 = pygame.image.load('historie17.png')
    hq18 = pygame.image.load('historie18.png')
    hq19 = pygame.image.load('historie19.png')
    hq20 = pygame.image.load('historie20.png')
    hq21 = pygame.image.load('historie21.png')
    hq22 = pygame.image.load('historie22.png')
    hq23 = pygame.image.load('historie23.png')
    hq24 = pygame.image.load('historie24.png')
    sq1 = pygame.image.load('sport1.png')
    sq2 = pygame.image.load('sport2.png')
    sq3 = pygame.image.load('sport3.png')
    sq4 = pygame.image.load('sport4.png')
    sq5 = pygame.image.load('sport5.png')
    sq6 = pygame.image.load('sport6.png')
    sq7 = pygame.image.load('sport7.png')
    sq8 = pygame.image.load('sport8.png')
    sq9 = pygame.image.load('sport9.png')
    sq10 = pygame.image.load('sport10.png')
    sq11 = pygame.image.load('sport11.png')
    sq12 = pygame.image.load('sport12.png')
    sq13 = pygame.image.load('sport13.png')
    sq14 = pygame.image.load('sport14.png')
    sq15 = pygame.image.load('sport15.png')
    sq16 = pygame.image.load('sport16.png')
    sq17 = pygame.image.load('sport17.png')
    sq18 = pygame.image.load('sport18.png')
    sq19 = pygame.image.load('sport19.png')
    sq20 = pygame.image.load('sport20.png')
    sq21 = pygame.image.load('sport21.png')
    sq22 = pygame.image.load('sport22.png')
    sq23 = pygame.image.load('sport23.png')
    sq24 = pygame.image.load('sport24.png')

    def qmusic():
        pygame.mixer.music.load('8bitquestion.mp3')
        pygame.mixer.music.play(loops=1, start=0.0)

    def qimg(img):
        scherm.blit(pygame.transform.scale(img, (display_width / 2, display_height / 2)), (50, 50))
    for q in range(0, 1, 1):
       n = random.randint(1, 24)
       if n == 1 and category == :
            qimg(eq1)
            #A is juist
            button("A. De Witte Aap", qbuttonposx, qbutton1ypos, qbuttonwidth, qbuttonheight, qred , qred, "opt2")
            button("B. Het NRC", qbuttonposx, qbutton2ypos, qbuttonwidth, qbuttonheight, qred, qred, "opt1")
            button("C. Café de Beurs", qbuttonposx, qbutton3ypos, qbuttonwidth, qbuttonheight, qred, qred, "opt1")
            qmusic()
            pygame.display.flip()
       elif n == 2 and category == :
           qimg(eq2)
           #B is juist
           button("A. R'dam Escape", qbuttonposx, qbutton1ypos, qbuttonwidth, qbuttonheight, qred, qred, "opt1")
           button("B. Escape010", qbuttonposx, qbutton2ypos, qbuttonwidth, qbuttonheight, qred, qred, "opt2")
           button("C. Room Escape", qbuttonposx, qbutton3ypos, qbuttonwidth, qbuttonheight, qred, qred, "opt1")
           qmusic()
           pygame.display.flip()
       elif n == 3 and category == :
           #C is juist
           qimg(eq3)
           button("A. Segway", qbuttonposx, qbutton1ypos, qbuttonwidth, qbuttonheight, qred, qred, "opt1")
           button("B. Boot", qbuttonposx, qbutton2ypos, qbuttonwidth, qbuttonheight, qred, qred, "opt1")
           button("C. Auto", qbuttonposx, qbutton3ypos, qbuttonwidth, qbuttonheight, qred, qred, "opt2")
           qmusic()
           pygame.display.flip()
       elif n == 4 and category == :
           #B is juist
           qimg(eq4)
           button("A. H&M", qbuttonposx, qbutton1ypos, qbuttonwidth, qbuttonheight, qred, qred, "opt1")
           button("B. Mediamarkt", qbuttonposx, qbutton2ypos, qbuttonwidth, qbuttonheight, qred, qred, "opt2")
           button("C. The Sting", qbuttonposx, qbutton3ypos, qbuttonwidth, qbuttonheight, qred, qred, "opt1")
           qmusic()
           pygame.display.flip()
       elif n == 5 and category == :
           #A is juist
           qimg(eq5)
           button("A. Cinerama", qbuttonposx, qbutton1ypos, qbuttonwidth, qbuttonheight, qred, qred, "opt2")
           button("B. Pathe De Kuip", qbuttonposx, qbutton2ypos, qbuttonwidth, qbuttonheight, qred, qred, "opt1")
           button("C. Pathe Schouwburgplein", qbuttonposx, qbutton3ypos, qbuttonwidth, qbuttonheight, qred, qred, "opt1")
           qmusic()
           pygame.display.flip()
       elif n == 6 and category == :
           #C is juist
           qimg(eq6)
           button("A. Havenmuseum", qbuttonposx, qbutton1ypos, qbuttonwidth, qbuttonheight, qred, qred, "opt1")
           button("B. Mariniersmuseum", qbuttonposx, qbutton2ypos, qbuttonwidth, qbuttonheight, qred, qred, "opt1")
           button("C. Maritiemmuseum", qbuttonposx, qbutton3ypos, qbuttonwidth, qbuttonheight, qred, qred, "opt2")
           qmusic()
           pygame.display.flip()
       elif n == 7 and category == :
           #C is juist
           qimg(eq7)
           button("A. De Euromast", qbuttonposx, qbutton1ypos, qbuttonwidth, qbuttonheight, qred, qred, "opt1")
           button("B. Museumplein", qbuttonposx, qbutton2ypos, qbuttonwidth, qbuttonheight, qred, qred, "opt1")
           button("C. De Markthal", qbuttonposx, qbutton3ypos, qbuttonwidth, qbuttonheight, qred, qred, "opt2")
           qmusic()
           pygame.display.flip()
       elif n == 8 and category == :
           #B is juist
           qimg(eq8)
           button("A. Pathe de Kuip", qbuttonposx, qbutton1ypos, qbuttonwidth, qbuttonheight, qred, qred, "opt1")
           button("B. Pathe de Kroon", qbuttonposx, qbutton2ypos, qbuttonwidth, qbuttonheight, qred, qred, "opt2")
           button("C. Pathe Schouwburgplein", qbuttonposx, qbutton3ypos, qbuttonwidth, qbuttonheight, qred, qred, "opt1")
           qmusic()
           pygame.display.flip()
       elif n == 9 and category == :
           #A is juist
           qimg(eq9)
           button("A. 925000 bezoekers", qbuttonposx, qbutton1ypos, qbuttonwidth, qbuttonheight, qred, qred, "opt2")
           button("B. 675000 bezoekers", qbuttonposx, qbutton2ypos, qbuttonwidth, qbuttonheight, qred, qred, "opt1")
           button("C. 830000 bezoekers", qbuttonposx, qbutton3ypos, qbuttonwidth, qbuttonheight, qred, qred, "opt1")
           qmusic()
           pygame.display.flip()
       elif n == 10 and category == :
           qimg(eq10)
           #B is juist
           button("A. Hoek van Holland", qbuttonposx, qbutton1ypos, qbuttonwidth, qbuttonheight, qred, qred, "opt1")
           button("B. Euromast Park", qbuttonposx, qbutton2ypos, qbuttonwidth, qbuttonheight, qred, qred, "opt2")
           button("C. Plaswijckpark", qbuttonposx, qbutton3ypos, qbuttonwidth, qbuttonheight, qred, qred, "opt1")
           qmusic()
           pygame.display.flip()
       elif n == 11 and category == :
           #A is juist
           qimg(eq11)
           button("A. Luxemburg en België", qbuttonposx, qbutton1ypos, qbuttonwidth, qbuttonheight, qred, qred, "opt2")
           button("B. Duitsland en België", qbuttonposx, qbutton2ypos, qbuttonwidth, qbuttonheight, qred, qred, "opt1")
           button("C. Duitsland en Frankrijk", qbuttonposx, qbutton3ypos, qbuttonwidth, qbuttonheight, qred, qred, "opt1")
           qmusic()
           pygame.display.flip()
       elif n == 12 and category == :
           qimg(eq12)
           #C is juist
           button("A. Drive & Eat", qbuttonposx, qbutton1ypos, qbuttonwidth, qbuttonheight, qred, qred, "opt1")
           button("B. Bicycle Diner", qbuttonposx, qbutton2ypos, qbuttonwidth, qbuttonheight, qred, qred, "opt1")
           button("C. Bike & Bite", qbuttonposx, qbutton3ypos, qbuttonwidth, qbuttonheight, qred, qred, "opt2")
           qmusic()
           pygame.display.flip()
       elif n == 13 and category == :
           #A is juist
           qimg(eq13)
           button("A. De Zwanenboot", qbuttonposx, qbutton1ypos, qbuttonwidth, qbuttonheight, qred, qred, "opt2")
           button("B. De Pannenkoekenboot", qbuttonposx, qbutton2ypos, qbuttonwidth, qbuttonheight, qred, qred, "opt1")
           button("C. De Berenboot", qbuttonposx, qbutton3ypos, qbuttonwidth, qbuttonheight, qred, qred, "opt1")
           qmusic()
           pygame.display.flip()
       elif n == 14 and category == :
           #C is juist
           qimg(eq14)
           button("A. Cinerama", qbuttonposx, qbutton1ypos, qbuttonwidth, qbuttonheight, qred, qred, "opt1")
           button("B. Pathe de Kuip", qbuttonposx, qbutton2ypos, qbuttonwidth, qbuttonheight, qred, qred, "opt1")
           button("C. LantarenVenster", qbuttonposx, qbutton3ypos, qbuttonwidth, qbuttonheight, qred, qred, "opt2")
           qmusic()
           pygame.display.flip()
       elif n == 15 and category == :
           qimg(eq15)
           #A is juist
           button("A. Mullerpier", qbuttonposx, qbutton1ypos, qbuttonwidth, qbuttonheight, qred, qred, "opt2")
           button("B. Pier 80", qbuttonposx, qbutton2ypos, qbuttonwidth, qbuttonheight, qred, qred, "opt1")
           button("C. Schouwburgplein", qbuttonposx, qbutton3ypos, qbuttonwidth, qbuttonheight, qred, qred, "opt1")
           qmusic()
           pygame.display.flip()
       elif n == 16 and category == :
           #A is juist
           qimg(eq16)
           button("A. De Witte de Withstraat", qbuttonposx, qbutton1ypos, qbuttonwidth, qbuttonheight, qred, qred, "opt2")
           button("B. Kruiskade", qbuttonposx, qbutton2ypos, qbuttonwidth, qbuttonheight, qred, qred, "opt1")
           button("C. Doedesstraat", qbuttonposx, qbutton3ypos, qbuttonwidth, qbuttonheight, qred, qred, "opt1")
           qmusic()
           pygame.display.flip()
       elif n == 17 and category == :
           #C is juist
           qimg(eq17)
           button("A. Willemsbrug", qbuttonposx, qbutton1ypos, qbuttonwidth, qbuttonheight, qred, qred, "opt1")
           button("B. Spaansebrug", qbuttonposx, qbutton2ypos, qbuttonwidth, qbuttonheight, qred, qred, "opt1")
           button("C. Erasmusbrug", qbuttonposx, qbutton3ypos, qbuttonwidth, qbuttonheight, qred, qred, "opt2")
           qmusic()
           pygame.display.flip()
       elif n == 18:
           #C is juist
           qimg(eq18)
           button("A. Noordelijk Film Festival", qbuttonposx, qbutton1ypos, qbuttonwidth, qbuttonheight, qred, qred, "opt1")
           button("B. Vlier Film Festival", qbuttonposx, qbutton2ypos, qbuttonwidth, qbuttonheight, qred, qred, "opt1")
           button("C. Internationaal Film Festival", qbuttonposx, qbutton3ypos, qbuttonwidth, qbuttonheight, qred, qred, "opt2")
           qmusic()
           pygame.display.flip()
       elif n == 19 and category == :
           #A is juist
           qimg(eq19)
           button("A. Diergaarde Blijdorp", qbuttonposx, qbutton1ypos, qbuttonwidth, qbuttonheight, qred, qred, "opt2")
           button("B. Plaswijckpark", qbuttonposx, qbutton2ypos, qbuttonwidth, qbuttonheight, qred, qred, "opt1")
           button("C. Utropia", qbuttonposx, qbutton3ypos, qbuttonwidth, qbuttonheight, qred, qred, "opt1")
           qmusic()
           pygame.display.flip()
       elif n == 20 and category == :
           #A is juist
           qimg(eq20)
           button("A. De Markthal", qbuttonposx, qbutton1ypos, qbuttonwidth, qbuttonheight, qred, qred, "opt2")
           button("B. De Verwoeste Stad", qbuttonposx, qbutton2ypos, qbuttonwidth, qbuttonheight, qred, qred, "opt1")
           button("C. De Boeg", qbuttonposx, qbutton3ypos, qbuttonwidth, qbuttonheight, qred, qred, "opt1")
           qmusic()
           pygame.display.flip()
       elif n == 21 and category == :
           #B is juist
           qimg(eq21)
           button("A. Wijnhaven", qbuttonposx, qbutton1ypos, qbuttonwidth, qbuttonheight, qred, qred, "opt1")
           button("B. Rijnhaven", qbuttonposx, qbutton2ypos, qbuttonwidth, qbuttonheight, qred, qred, "opt2")
           button("C. Parkhaven", qbuttonposx, qbutton3ypos, qbuttonwidth, qbuttonheight, qred, qred, "opt1")
           qmusic()
           pygame.display.flip()
       elif n == 22 and category == :
           #B is juist
           qimg(eq22)
           button("A. Rotterdam Creeper Walk", qbuttonposx, qbutton1ypos, qbuttonwidth, qbuttonheight, qred, qred, "opt1")
           button("B. Rotterdam Zombie Walk", qbuttonposx, qbutton2ypos, qbuttonwidth, qbuttonheight, qred, qred, "opt2")
           button("C. Rotterdam Undead Walk", qbuttonposx, qbutton3ypos, qbuttonwidth, qbuttonheight, qred, qred, "opt1")
           qmusic()
           pygame.display.flip()
       elif n == 23 and category == :
           #C is juist
           qimg(eq23)
           button("A. Rotterdam Gaypride", qbuttonposx, qbutton1ypos, qbuttonwidth, qbuttonheight, qred, qred, "opt1")
           button("B. Rotterdam LGBT parade", qbuttonposx, qbutton2ypos, qbuttonwidth, qbuttonheight, qred, qred, "opt1")
           button("C. Rotterdam Pride", qbuttonposx, qbutton3ypos, qbuttonwidth, qbuttonheight, qred, qred, "opt2")
           qmusic()
           pygame.display.flip()
       elif n == 24 and category == :
           #B is juist
           qimg(eq24)
           button("A. Januari", qbuttonposx, qbutton1ypos, qbuttonwidth, qbuttonheight, qred, qred, "opt1")
           button("B. September", qbuttonposx, qbutton2ypos, qbuttonwidth, qbuttonheight, qred, qred, "opt2")
           button("C. Mei", qbuttonposx, qbutton3ypos, qbuttonwidth, qbuttonheight, qred, qred, "opt1")
           qmusic()
           pygame.display.flip()
       elif n == 1 and category == :
            qimg(hq1)
            button("A. Kooplieden hadden dit vroeger bedacht ", qbuttonposx, qbutton1ypos, qbuttonwidth, qbuttonheight, qyellow , qyellow, "opt1")
            button("B. Aan de rivier de rotte", qbuttonposx, qbutton2ypos, qbuttonwidth, qbuttonheight, qyellow, qyellow, "opt2")
            button("C. Er was een dam aangelegd in de maas", qbuttonposx, qbutton3ypos, qbuttonwidth, qbuttonheight, qyellow, qyellow, "opt1")
            qmusic()
            pygame.display.flip()
       elif n == 2 and category == :
            qimg(hq2)
            button("A. De oude haven", qbuttonposx, qbutton1ypos, qbuttonwidth, qbuttonheight, qyellow, qyellow, "opt1")
            button("B. VOC magazijn", qbuttonposx, qbutton2ypos, qbuttonwidth, qbuttonheight, qyellow, qyellow, "opt1")
            button("C. St. Laurenskerks", qbuttonposx, qbutton3ypos, qbuttonwidth, qbuttonheight, qyellow, qyellow, "opt2")
            qmusic()
            pygame.display.flip()
       elif n == 3 and category == :
            qimg(hq3)
            button("A. Ahmed Aboutaleb ", qbuttonposx, qbutton1ypos, qbuttonwidth, qbuttonheight, qyellow, qyellow, "opt1")
            button("B. Jules Deelder", qbuttonposx, qbutton2ypos, qbuttonwidth, qbuttonheight, qyellow, qyellow, "opt2")
            button("C. Willem Alexander", qbuttonposx, qbutton3ypos, qbuttonwidth, qbuttonheight, qyellow, qyellow, "opt1")
            qmusic()
            pygame.display.flip()
       elif n == 4 and category == :
            qimg(hq4)
            button("A. Waar", qbuttonposx, qbutton1ypos, qbuttonwidth, qbuttonheight, qyellow, qyellow, "opt2")
            button("B. Niet waar ", qbuttonposx, qbutton2ypos, qbuttonwidth, qbuttonheight, qyellow, qyellow, "opt1")
            qmusic()
            pygame.display.flip()
       elif n == 5 and category == :
            qimg(hq5)
            button("A. De beste bakker van de stad was daar gevestigd", qbuttonposx, qbutton1ypos, qbuttonwidth, qbuttonheight, qyellow, qyellow, "opt1")
            button("B. De prostituees", qbuttonposx, qbutton2ypos, qbuttonwidth, qbuttonheight, qyellow, qyellow, "opt2")
            button("C. De oudste beschermde boom van de stad staat daar", qbuttonposx, qbutton3ypos, qbuttonwidth, qbuttonheight, qyellow, qyellow, "opt1")
            qmusic()
            pygame.display.flip()
       elif n == 6 and category == :
            qimg(hq6)
            button("A. 1855", qbuttonposx, qbutton1ypos, qbuttonwidth, qbuttonheight, qyellow, qyellow, "opt2")
            button("B. 1975", qbuttonposx, qbutton2ypos, qbuttonwidth, qbuttonheight, qyellow, qyellow, "opt1")
            button("C. 1915", qbuttonposx, qbutton3ypos, qbuttonwidth, qbuttonheight, qyellow, qyellow, "opt1")
            qmusic()
            pygame.display.flip()
       elif n == 8 and category == :
            qimg(hq8)
            button("A. De Bijenkorf", qbuttonposx, qbutton1ypos, qbuttonwidth, qbuttonheight, qyellow, qyellow, "opt2")
            button("B. De Kubuswoningen", qbuttonposx, qbutton2ypos, qbuttonwidth, qbuttonheight, qyellow, qyellow, "opt1")
            button("C. The Red Apple", qbuttonposx, qbutton3ypos, qbuttonwidth, qbuttonheight, qyellow, qyellow, "opt1")
            qmusic()
            pygame.display.flip()
       elif n == 7 and category == :
            qimg(hq7)
            button("A. De ondergrondse winkelstraat", qbuttonposx, qbutton1ypos, qbuttonwidth, qbuttonheight, qyellow, qyellow, "opt1")
            button("B. Beurstraverse", qbuttonposx, qbutton2ypos, qbuttonwidth, qbuttonheight, qyellow, qyellow, "opt2")
            button("C. Gewoon de koopgoot", qbuttonposx, qbutton3ypos, qbuttonwidth, qbuttonheight, qyellow, qyellow, "opt1")
            qmusic()
            pygame.display.flip()
       elif n == 10 and category == :
            qimg(hq10)
            button("A. De nieuwe Binnenweg", qbuttonposx, qbutton1ypos, qbuttonwidth, qbuttonheight, qyellow, qyellow, "opt1")
            button("B. Maasbrug", qbuttonposx, qbutton2ypos, qbuttonwidth, qbuttonheight, qyellow, qyellow, "opt2")
            button("C. Koninginnenbrug", qbuttonposx, qbutton3ypos, qbuttonwidth, qbuttonheight, qyellow, qyellow, "opt1")
            qmusic()
            pygame.display.flip()
       elif n == 9 and category == :
            qimg(hq9)
            button("A. 5000", qbuttonposx, qbutton1ypos, qbuttonwidth, qbuttonheight, qyellow, qyellow, "opt1")
            button("B. 8000", qbuttonposx, qbutton2ypos, qbuttonwidth, qbuttonheight, qyellow, qyellow, "opt1")
            button("C. 12000", qbuttonposx, qbutton3ypos, qbuttonwidth, qbuttonheight, qyellow, qyellow, "opt2")
            qmusic()
            pygame.display.flip()
       elif n == 11 and category == :
            qimg(hq11)
            button("A. Suiker", qbuttonposx, qbutton1ypos, qbuttonwidth, qbuttonheight, qyellow, qyellow, "opt2")
            button("B. Wol", qbuttonposx, qbutton2ypos, qbuttonwidth, qbuttonheight, qyellow, qyellow, "opt2")
            button("C. Cacao", qbuttonposx, qbutton3ypos, qbuttonwidth, qbuttonheight, qyellow, qyellow, "opt1")
            qmusic()
            pygame.display.flip()
       elif n == 12 and category == :
            qimg(hq12)
            button("A. De Nieuwe Waterweg", qbuttonposx, qbutton1ypos, qbuttonwidth, qbuttonheight, qyellow, qyellow, "opt2")
            button("B. De Maas zeeverbinding", qbuttonposx, qbutton2ypos, qbuttonwidth, qbuttonheight, qyellow, qyellow, "opt1")
            button("C. Het Nieuwe Water kanaal", qbuttonposx, qbutton3ypos, qbuttonwidth, qbuttonheight, qyellow, qyellow, "opt1")
            qmusic()
            pygame.display.flip()
       elif n == 13 and category == :
            qimg(hq13)
            button("A. Maaskant", qbuttonposx, qbutton1ypos, qbuttonwidth, qbuttonheight, qyellow, qyellow, "opt2")
            button("B. Brinkman en van der Vlugt", qbuttonposx, qbutton2ypos, qbuttonwidth, qbuttonheight, qyellow, qyellow, "opt1")
            button("C. Koolhaas", qbuttonposx, qbutton3ypos, qbuttonwidth, qbuttonheight, qyellow, qyellow, "opt1")
            qmusic()
            pygame.display.flip()
       elif n == 14 and category == :
            qimg(hq14)
            button("A. 1250", qbuttonposx, qbutton1ypos, qbuttonwidth, qbuttonheight, qyellow, qyellow, "opt1")
            button("B. 1340", qbuttonposx, qbutton2ypos, qbuttonwidth, qbuttonheight, qyellow, qyellow, "opt2")
            button("C. 1590", qbuttonposx, qbutton3ypos, qbuttonwidth, qbuttonheight, qyellow, qyellow, "opt1")
            qmusic()
            pygame.display.flip()
       elif n == 15 and category == :
            qimg(hq15)
            button("A. De Witte Aap", qbuttonposx, qbutton1ypos, qbuttonwidth, qbuttonheight, qyellow, qyellow, "opt2")
            button("B. Het NRC", qbuttonposx, qbutton2ypos, qbuttonwidth, qbuttonheight, qyellow, qyellow, "opt1")
            button("C. Café de Beurs", qbuttonposx, qbutton3ypos, qbuttonwidth, qbuttonheight, qyellow, qyellow, "opt1")
            qmusic()
            pygame.display.flip()
       elif n == 16 and category == :
            qimg(hq16)
            button("A. GroenLinks", qbuttonposx, qbutton1ypos, qbuttonwidth, qbuttonheight, qyellow, qyellow, "opt1")
            button("B. DENK", qbuttonposx, qbutton2ypos, qbuttonwidth, qbuttonheight, qyellow, qyellow, "opt1")
            button("C. Leefbaar Rotterdam", qbuttonposx, qbutton3ypos, qbuttonwidth, qbuttonheight, qyellow, qyellow, "opt2")
            qmusic()
            pygame.display.flip()
       elif n == 17 and category == :
            qimg(hq17)
            button("A. Loods 21", qbuttonposx, qbutton1ypos, qbuttonwidth, qbuttonheight, qyellow, qyellow, "opt1")
            button("B. Loods 5", qbuttonposx, qbutton2ypos, qbuttonwidth, qbuttonheight, qyellow, qyellow, "opt1")
            button("C. Loods 24", qbuttonposx, qbutton3ypos, qbuttonwidth, qbuttonheight, qyellow, qyellow, "opt2")
            qmusic()
            pygame.display.flip()
       elif n == 18 and category == :
            qimg(hq18)
            button("A. Nederland-Amerika Lijn", qbuttonposx, qbutton1ypos, qbuttonwidth, qbuttonheight, qyellow, qyellow, "opt1")
            button("B. Holland-Amerika Lijn", qbuttonposx, qbutton2ypos, qbuttonwidth, qbuttonheight, qyellow, qyellow, "opt2")
            button("C. Rotterdam-Amerika Lijn", qbuttonposx, qbutton3ypos, qbuttonwidth, qbuttonheight, qyellow, qyellow, "opt1")
            qmusic()
            pygame.display.flip()
       elif n == 19 and category == :
            qimg(hq19)
            button("A. NRC", qbuttonposx, qbutton1ypos, qbuttonwidth, qbuttonheight, qyellow, qyellow, "opt2")
            button("B. De Telegraaf", qbuttonposx, qbutton2ypos, qbuttonwidth, qbuttonheight, qyellow, qyellow, "opt1")
            button("C. Metro", qbuttonposx, qbutton3ypos, qbuttonwidth, qbuttonheight, qyellow, qyellow, "opt1")
            qmusic()
            pygame.display.flip()
       elif n == 20 and category == :
            qimg(hq20)
            button("A. Nieuwe Roddel Courant", qbuttonposx, qbutton1ypos, qbuttonwidth, qbuttonheight, qyellow, qyellow, "opt1")
            button("B. Nieuwe Rotterdamsche Courant", qbuttonposx, qbutton2ypos, qbuttonwidth, qbuttonheight, qyellow, qyellow, "opt2")
            button("C. Nieuwe Reactie Courant", qbuttonposx, qbutton3ypos, qbuttonwidth, qbuttonheight, qyellow, qyellow, "opt1")
            qmusic()
            pygame.display.flip()
       elif n == 21 and category == :
            qimg(hq21)
            button("A. Blaak 6", qbuttonposx, qbutton1ypos, qbuttonwidth, qbuttonheight, qyellow, qyellow, "opt1")
            button("B. Markthal", qbuttonposx, qbutton2ypos, qbuttonwidth, qbuttonheight, qyellow, qyellow, "opt1")
            button("C. Het witte Huis", qbuttonposx, qbutton3ypos, qbuttonwidth, qbuttonheight, qyellow, qyellow, "opt2")
            qmusic()
            pygame.display.flip()
       elif n == 22 and category == :
            qimg(hq22)
            button("A. 1939-1946", qbuttonposx, qbutton1ypos, qbuttonwidth, qbuttonheight, qyellow, qyellow, "opt1")
            button("B. 1935-1940", qbuttonposx, qbutton2ypos, qbuttonwidth, qbuttonheight, qyellow, qyellow, "opt1")
            button("C. 1940-1945", qbuttonposx, qbutton3ypos, qbuttonwidth, qbuttonheight, qyellow, qyellow, "opt2")
            qmusic()
            pygame.display.flip()
       elif n == 23 and category == :
            qimg(hq23)
            button("A. De verwoeste Stad", qbuttonposx, qbutton1ypos, qbuttonwidth, qbuttonheight, qyellow, qyellow, "opt2")
            button("B. Kabouter Buttplug", qbuttonposx, qbutton2ypos, qbuttonwidth, qbuttonheight, qyellow, qyellow, "opt1")
            button("C. Erasmusbeeld", qbuttonposx, qbutton3ypos, qbuttonwidth, qbuttonheight, qyellow, qyellow, "opt1")
            qmusic()
            pygame.display.flip()
       elif n == 24 and category == :
            qimg(hq24)
            button("A. Nederland-Amerika lijn", qbuttonposx, qbutton1ypos, qbuttonwidth, qbuttonheight, qyellow, qyellow, "opt1")
            button("B. Rotterdam-Amerika Lijn", qbuttonposx, qbutton2ypos, qbuttonwidth, qbuttonheight, qyellow, qyellow, "opt1")
            button("C. Holland-Amerika lijn", qbuttonposx, qbutton3ypos, qbuttonwidth, qbuttonheight, qyellow, qyellow, "opt2")
            qmusic()
            pygame.display.flip()
       elif n == 1 and category == :
           qimg(gq1)
           button("A. Kerktoren hillegondakerk", qbuttonposx, qbutton1ypos, qbuttonwidth, qbuttonheight, qgreen, qgreen, "opt2")
           button("B. St. Laurenskerk.", qbuttonposx, qbutton2ypos, qbuttonwidth, qbuttonheight, qgreen, qgreen, "opt1")
           button("C. Stadhuis van Rotterdam", qbuttonposx, qbutton3ypos, qbuttonwidth, qbuttonheight, qgreen, qgreen, "opt1")
           qmusic()
           pygame.display.flip()
       elif n == 2 and category == :
           qimg(gq2)
           button("A. 800.000", qbuttonposx, qbutton1ypos, qbuttonwidth, qbuttonheight, qgreen, qgreen, "opt1")
           button("B. 900.000", qbuttonposx, qbutton2ypos, qbuttonwidth, qbuttonheight, qgreen, qgreen, "opt1")
           button("C. 1.000.000", qbuttonposx, qbutton3ypos, qbuttonwidth, qbuttonheight, qgreen, qgreen, "opt2")
           qmusic()
           pygame.display.flip()
       elif n == 3 and category == :
           qimg(gq3)
           button("A. De Willemsbrug", qbuttonposx, qbutton1ypos, qbuttonwidth, qbuttonheight, qgreen, qgreen, "opt1")
           button("B. De Koninginnebrug", qbuttonposx, qbutton2ypos, qbuttonwidth, qbuttonheight, qgreen, qgreen, "opt2")
           button("C. De van Briennenoordbrug", qbuttonposx, qbutton3ypos, qbuttonwidth, qbuttonheight, qgreen, qgreen, "opt1")
           qmusic()
           pygame.display.flip()
       elif n == 4 and category == :
           qimg(gq4)
           button("A. Stad der Wonderen", qbuttonposx, qbutton1ypos, qbuttonwidth, qbuttonheight, qgreen, qgreen, "opt1")
           button("B. Stad der Steden", qbuttonposx, qbutton2ypos, qbuttonwidth, qbuttonheight, qgreen, qgreen, "opt1")
           button("C. Havenstad", qbuttonposx, qbutton3ypos, qbuttonwidth, qbuttonheight, qgreen, qgreen, "opt2")
           qmusic()
           pygame.display.flip()
       elif n == 5 and category == :
           qimg(gq5)
           button("A. Noord-Holland", qbuttonposx, qbutton1ypos, qbuttonwidth, qbuttonheight, qgreen, qgreen, "opt1")
           button("B. Zuid-Holland", qbuttonposx, qbutton2ypos, qbuttonwidth, qbuttonheight, qgreen, qgreen, "opt2")
           button("C. Noord-Brabant", qbuttonposx, qbutton3ypos, qbuttonwidth, qbuttonheight, qgreen, qgreen, "opt1")
           qmusic()
           pygame.display.flip()
       elif n == 6 and category == :
           qimg(gq6)
           button("A. De Maas", qbuttonposx, qbutton1ypos, qbuttonwidth, qbuttonheight, qgreen, qgreen, "opt2")
           button("B. De Rijn", qbuttonposx, qbutton2ypos, qbuttonwidth, qbuttonheight, qgreen, qgreen, "opt1")
           button("C. De Waal", qbuttonposx, qbutton3ypos, qbuttonwidth, qbuttonheight, qgreen, qgreen, "opt1")
           qmusic()
           pygame.display.flip()
       elif n == 7 and category == :
           qimg(gq7)
           button("A. 50 tot 60km", qbuttonposx, qbutton1ypos, qbuttonwidth, qbuttonheight, qgreen, qgreen, "opt1")
           button("B. 60 tot 70km", qbuttonposx, qbutton2ypos, qbuttonwidth, qbuttonheight, qgreen, qgreen, "opt1")
           button("C. 70 tot 80km", qbuttonposx, qbutton3ypos, qbuttonwidth, qbuttonheight, qgreen, qgreen, "opt2")
           qmusic()
           pygame.display.flip()
       elif n == 8 and category == :
           qimg(gq8)
           button("A. De Witte Aap", qbuttonposx, qbutton1ypos, qbuttonwidth, qbuttonheight, qgreen, qgreen, "opt1")
           button("B. Het NRC", qbuttonposx, qbutton2ypos, qbuttonwidth, qbuttonheight, qgreen, qgreen, "opt2")
           button("C. Café de Beurs", qbuttonposx, qbutton3ypos, qbuttonwidth, qbuttonheight, qgreen, qgreen, "opt3")
           qmusic()
           pygame.display.flip()
       elif n == 9 and category == :
           qimg(gq9)
           button("A. De Willemsbrug", qbuttonposx, qbutton1ypos, qbuttonwidth, qbuttonheight, qgreen, qgreen, "opt1")
           button("B. De Erasmusbrug", qbuttonposx, qbutton2ypos, qbuttonwidth, qbuttonheight, qgreen, qgreen, "opt2")
           button("C. De van Briennenoordbrug", qbuttonposx, qbutton3ypos, qbuttonwidth, qbuttonheight, qgreen, qgreen, "opt1")
           qmusic()
           pygame.display.flip()
       elif n == 10 and category == :
           qimg(gq10)
           button("A. Waar", qbuttonposx, qbutton1ypos, qbuttonwidth, qbuttonheight, qgreen, qgreen, "opt2")
           button("B. Niet waar", qbuttonposx, qbutton2ypos, qbuttonwidth, qbuttonheight, qgreen, qgreen, "opt1")
           qmusic()
           pygame.display.flip()
       elif n == 11 and category == :
           qimg(gq11)
           button("A. Waar", qbuttonposx, qbutton1ypos, qbuttonwidth, qbuttonheight, qgreen, qgreen, "opt2")
           button("B. Niet Waar", qbuttonposx, qbutton2ypos, qbuttonwidth, qbuttonheight, qgreen, qgreen, "opt1")
           qmusic()
           pygame.display.flip()
       elif n == 12 and category == :
           qimg(gq12)
           button("A. Waar", qbuttonposx, qbutton1ypos, qbuttonwidth, qbuttonheight, qgreen, qgreen, "opt2")
           button("B. Niet waar", qbuttonposx, qbutton2ypos, qbuttonwidth, qbuttonheight, qgreen, qgreen, "opt1")
           qmusic()
           pygame.display.flip()
       elif n == 13 and category == :
           qimg(gq13)
           button("A. Metro", qbuttonposx, qbutton1ypos, qbuttonwidth, qbuttonheight, qgreen, qgreen, "opt2")
           button("B. Auto", qbuttonposx, qbutton2ypos, qbuttonwidth, qbuttonheight, qgreen, qgreen, "opt1")
           button("C. Fiets", qbuttonposx, qbutton3ypos, qbuttonwidth, qbuttonheight, qgreen, qgreen, "opt1")
           qmusic()
           pygame.display.flip()
       elif n == 14 and category == :
           qimg(gq14)
           button("A. 760 tot 780mm", qbuttonposx, qbutton1ypos, qbuttonwidth, qbuttonheight, qgreen, qgreen, "opt1")
           button("B. 780 tot 800mm", qbuttonposx, qbutton2ypos, qbuttonwidth, qbuttonheight, qgreen, qgreen, "opt1")
           button("C. 800 tot 820mm", qbuttonposx, qbutton3ypos, qbuttonwidth, qbuttonheight, qgreen, qgreen, "opt2")
           qmusic()
           pygame.display.flip()
       elif n == 15 and category == :
           qimg(gq15)
           button("A. 150.000", qbuttonposx, qbutton1ypos, qbuttonwidth, qbuttonheight, qgreen, qgreen, "opt1")
           button("B. 300.000", qbuttonposx, qbutton2ypos, qbuttonwidth, qbuttonheight, qgreen, qgreen, "opt2")
           button("C. 450.000", qbuttonposx, qbutton3ypos, qbuttonwidth, qbuttonheight, qgreen, qgreen, "opt1")
           qmusic()
           pygame.display.flip()
       elif n == 16 and category == :
           qimg(gq16)
           button("A. 327,6 km2", qbuttonposx, qbutton1ypos, qbuttonwidth, qbuttonheight, qgreen, qgreen, "opt1")
           button("B. 319,4 km2", qbuttonposx, qbutton2ypos, qbuttonwidth, qbuttonheight, qgreen, qgreen, "opt2")
           button("C. 352,8 km2", qbuttonposx, qbutton3ypos, qbuttonwidth, qbuttonheight, qgreen, qgreen, "opt1")
           qmusic()
           pygame.display.flip()
       elif n == 17 and category == :
           qimg(gq17)
           button("A. 180 meter", qbuttonposx, qbutton1ypos, qbuttonwidth, qbuttonheight, qgreen, qgreen, "opt1")
           button("B. 195 meter", qbuttonposx, qbutton2ypos, qbuttonwidth, qbuttonheight, qgreen, qgreen, "opt1")
           button("C. 185 meter", qbuttonposx, qbutton3ypos, qbuttonwidth, qbuttonheight, qgreen, qgreen, "opt2")
           qmusic()
           pygame.display.flip()
       elif n == 18 and category == :
           qimg(gq18)
           button("A. De Maastoren", qbuttonposx, qbutton1ypos, qbuttonwidth, qbuttonheight, qgreen, qgreen, "opt2")
           button("B. De Boeg", qbuttonposx, qbutton2ypos, qbuttonwidth, qbuttonheight, qgreen, qgreen, "opt1")
           button("C. Euromast", qbuttonposx, qbutton3ypos, qbuttonwidth, qbuttonheight, qgreen, qgreen, "opt1")
           qmusic()
           pygame.display.flip()
       elif n == 19 and category == :
           qimg(gq19)
           button("A. Markthalwoningen", qbuttonposx, qbutton1ypos, qbuttonwidth, qbuttonheight, qgreen, qgreen, "opt1")
           button("B. Blaakwoningen", qbuttonposx, qbutton2ypos, qbuttonwidth, qbuttonheight, qgreen, qgreen, "opt1")
           button("C. De Kubuswoningen", qbuttonposx, qbutton3ypos, qbuttonwidth, qbuttonheight, qgreen, qgreen, "opt2")
           qmusic()
           pygame.display.flip()
       elif n == 20 and category == :
           qimg(gq20)
           button("A. De Rotterdamse berg", qbuttonposx, qbutton1ypos, qbuttonwidth, qbuttonheight, qgreen, qgreen, "opt1")
           button("B. De Courantse berg", qbuttonposx, qbutton2ypos, qbuttonwidth, qbuttonheight, qgreen, qgreen, "opt1")
           button("C. Rotterdam heeft geen bergen", qbuttonposx, qbutton3ypos, qbuttonwidth, qbuttonheight, qgreen, qgreen, "opt2")
           qmusic()
           pygame.display.flip()
       elif n == 21 and category == :
           qimg(gq21)
           button("A. Koopgoot kerstboom", qbuttonposx, qbutton1ypos, qbuttonwidth, qbuttonheight, qgreen, qgreen, "opt1")
           button("B. Kabouter Buttplug", qbuttonposx, qbutton2ypos, qbuttonwidth, qbuttonheight, qgreen, qgreen, "opt2")
           button("C. Erasmus kerstboom", qbuttonposx, qbutton3ypos, qbuttonwidth, qbuttonheight, qgreen, qgreen, "opt1")
           qmusic()
           pygame.display.flip()
       elif n == 22 and category == :
           qimg(gq22)
           button("A. Rotterdam is de grootste stad van Nederland", qbuttonposx, qbutton1ypos, qbuttonwidth, qbuttonheight, qgreen, qgreen, "opt2")
           button("B. Den Haag", qbuttonposx, qbutton2ypos, qbuttonwidth, qbuttonheight, qgreen, qgreen, "opt1")
           button("C. Amsterdam", qbuttonposx, qbutton3ypos, qbuttonwidth, qbuttonheight, qgreen, qgreen, "opt1")
           qmusic()
           pygame.display.flip()
       elif n == 23 and category == :
           qimg(gq23)
           button("A. Tropisch klimaat", qbuttonposx, qbutton1ypos, qbuttonwidth, qbuttonheight, qgreen, qgreen, "opt1")
           button("B. Droog klimaat", qbuttonposx, qbutton2ypos, qbuttonwidth, qbuttonheight, qgreen, qgreen, "opt1")
           button("C. Gematigd klimaat", qbuttonposx, qbutton3ypos, qbuttonwidth, qbuttonheight, qgreen, qgreen, "opt2")
           qmusic()
           pygame.display.flip()
       elif n == 24 and category == :
           qimg(gq24)
           button("A. De Willemsbrug", qbuttonposx, qbutton1ypos, qbuttonwidth, qbuttonheight, qgreen, qgreen, "opt1")
           button("B. De Erasmusbrug", qbuttonposx, qbutton2ypos, qbuttonwidth, qbuttonheight, qgreen, qgreen, "opt2")
           button("C. De Hef", qbuttonposx, qbutton3ypos, qbuttonwidth, qbuttonheight, qgreen, qgreen, "opt1")
           qmusic()
           pygame.display.flip()
       elif n == 1 and category == :
           qimg(sq1)
           button("A. 2000", qbuttonposx, qbutton1ypos, qbuttonwidth, qbuttonheight, qgreen, qgreen, "opt1")
           button("B. 2005", qbuttonposx, qbutton2ypos, qbuttonwidth, qbuttonheight, qgreen, qgreen, "opt1")
           button("C. 2010", qbuttonposx, qbutton3ypos, qbuttonwidth, qbuttonheight, qgreen, qgreen, "opt2")
           qmusic()
           pygame.display.flip()
       elif n == 2 and category == :
           qimg(sq2)
           button("A. ABN AMRO World Tennis Tournament", qbuttonposx, qbutton1ypos, qbuttonwidth, qbuttonheight, qblue, qblue, "opt2")
           button("B. Ahoy Open", qbuttonposx, qbutton2ypos, qbuttonwidth, qbuttonheight, qblue, qblue, "opt1")
           button("C. Heineken Open", qbuttonposx, qbutton3ypos, qbuttonwidth, qbuttonheight, qblue, qblue, "opt1")
           qmusic()
           pygame.display.flip()
       elif n == 3 and category == :
           qimg(sq3)
           button("A. HVGR", qbuttonposx, qbutton1ypos, qbuttonwidth, qbuttonheight, qblue, qblue, "opt1")
           button("B. Focus", qbuttonposx, qbutton2ypos, qbuttonwidth, qbuttonheight, qblue, qblue, "opt1")
           button("C. HC Rotterdam", qbuttonposx, qbutton3ypos, qbuttonwidth, qbuttonheight, qblue, qblue, "opt2")
           qmusic()
           pygame.display.flip()
       elif n == 4 and category == :
           qimg(sq4)
           button("A. Fitness", qbuttonposx, qbutton1ypos, qbuttonwidth, qbuttonheight, qblue, qblue, "opt2")
           button("B. Voetbal", qbuttonposx, qbutton2ypos, qbuttonwidth, qbuttonheight, qblue, qblue, "opt1")
           button("C. Basketbal", qbuttonposx, qbutton3ypos, qbuttonwidth, qbuttonheight, qblue, qblue, "opt1")
           qmusic()
           pygame.display.flip()
       elif n == 5 and category == :
           qimg(sq5)
           button("A. Dorian van Rijsselberghe", qbuttonposx, qbutton1ypos, qbuttonwidth, qbuttonheight, qblue, qblue, "opt1")
           button("B. Marhinde Verkerk", qbuttonposx, qbutton2ypos, qbuttonwidth, qbuttonheight, qblue, qblue, "opt2")
           button("C. Edith Bosch", qbuttonposx, qbutton3ypos, qbuttonwidth, qbuttonheight, qblue, qblue, "opt1")
           qmusic()
           pygame.display.flip()
       elif n == 6 and category == :
           qimg(sq6)
           button("A. Willem Alexander baan", qbuttonposx, qbutton1ypos, qbuttonwidth, qbuttonheight, qblue, qblue, "opt2")
           button("B. Beatrix baan", qbuttonposx, qbutton2ypos, qbuttonwidth, qbuttonheight, qblue, qblue, "opt1")
           button("C. Juliana baan", qbuttonposx, qbutton3ypos, qbuttonwidth, qbuttonheight, qblue, qblue, "opt1")
           qmusic()
           pygame.display.flip()
       elif n == 7 and category == :
           qimg(sq7)
           button("A. Watersporten, Wielrennen en hardlopen", qbuttonposx, qbutton1ypos, qbuttonwidth, qbuttonheight, qblue, qblue, "opt2")
           button("B. Voetbal, Hockey en basketbal", qbuttonposx, qbutton2ypos, qbuttonwidth, qbuttonheight, qblue, qblue, "opt1")
           button("C. Fitness, hardlopen en basketbal", qbuttonposx, qbutton3ypos, qbuttonwidth, qbuttonheight, qblue, qblue, "opt1")
           qmusic()
           pygame.display.flip()
       elif n == 8 and category == :
           qimg(sq8)
           button("A. Rechtsback", qbuttonposx, qbutton1ypos, qbuttonwidth, qbuttonheight, qblue, qblue, "opt1")
           button("B. Linksback", qbuttonposx, qbutton2ypos, qbuttonwidth, qbuttonheight, qblue, qblue, "opt1")
           button("C. Linksbuiten", qbuttonposx, qbutton3ypos, qbuttonwidth, qbuttonheight, qblue, qblue, "opt2")
           qmusic()
           pygame.display.flip()
       elif n == 11 and category == :
           qimg(sq11)
           button("A. 42,125 km", qbuttonposx, qbutton1ypos, qbuttonwidth, qbuttonheight, qblue, qblue, "opt2")
           button("B. 42,450 km", qbuttonposx, qbutton2ypos, qbuttonwidth, qbuttonheight, qblue, qblue, "opt1")
           button("C. 42,680 km", qbuttonposx, qbutton3ypos, qbuttonwidth, qbuttonheight, qblue, qblue, "opt1")
           qmusic()
           pygame.display.flip()
       elif n == 9 and category == :
           qimg(sq9)
           button("A. Zich verder van het doel bevindt dan de keeper.", qbuttonposx, qbutton1ypos, qbuttonwidth, qbuttonheight, qblue, qblue, "opt1")
           button("B. Zich dichter bij de doellijn van de tegenstander bevindt dan de bal en de vóórlaatste tegenstander.", qbuttonposx, qbutton2ypos, qbuttonwidth, qbuttonheight, qblue, qblue, "opt2")
           button("C. Zich buiten de lijn van het veld bevindt en de bal in het spel is.", qbuttonposx, qbutton3ypos, qbuttonwidth, qbuttonheight, qblue, qblue, "opt1")
           qmusic()
           pygame.display.flip()
       elif n == 10 and category == :
           qimg(sq10)
           button("A. De Toren", qbuttonposx, qbutton1ypos, qbuttonwidth, qbuttonheight, qblue, qblue, "opt1")
           button("B. Het Kasteel", qbuttonposx, qbutton2ypos, qbuttonwidth, qbuttonheight, qblue, qblue, "opt2")
           button("C. De Arena", qbuttonposx, qbutton3ypos, qbuttonwidth, qbuttonheight, qblue, qblue, "opt1")
           qmusic()
           pygame.display.flip()
       elif n == 12 and category == :
           qimg(sq12)
           button("A. 9", qbuttonposx, qbutton1ypos, qbuttonwidth, qbuttonheight, qblue, qblue, "opt1")
           button("B. 10", qbuttonposx, qbutton2ypos, qbuttonwidth, qbuttonheight, qblue, qblue, "opt2")
           button("C. 11", qbuttonposx, qbutton3ypos, qbuttonwidth, qbuttonheight, qblue, qblue, "opt1")
           qmusic()
           pygame.display.flip()
       elif n == 13 and category == :
           qimg(sq13)
           button("A. 1850", qbuttonposx, qbutton1ypos, qbuttonwidth, qbuttonheight, qblue, qblue, "opt1")
           button("B. 1875 ", qbuttonposx, qbutton2ypos, qbuttonwidth, qbuttonheight, qblue, qblue, "opt1")
           button("C. 1900", qbuttonposx, qbutton3ypos, qbuttonwidth, qbuttonheight, qblue, qblue, "opt2")
           qmusic()
           pygame.display.flip()
       elif n == 14 and category == :
           qimg(sq14)
           button("A. Waar", qbuttonposx, qbutton1ypos, qbuttonwidth, qbuttonheight, qblue, qblue, "opt1")
           button("B. Niet waar", qbuttonposx, qbutton2ypos, qbuttonwidth, qbuttonheight, qblue, qblue, "opt2")
           button("C. Even groot", qbuttonposx, qbutton3ypos, qbuttonwidth, qbuttonheight, qblue, qblue, "opt1")
           qmusic()
           pygame.display.flip()
       elif n == 15 and category == :
           qimg(sq15)
           button("A. 1", qbuttonposx, qbutton1ypos, qbuttonwidth, qbuttonheight, qblue, qblue, "opt1")
           button("B. 2", qbuttonposx, qbutton2ypos, qbuttonwidth, qbuttonheight, qblue, qblue, "opt2")
           button("C. 3", qbuttonposx, qbutton3ypos, qbuttonwidth, qbuttonheight, qblue, qblue, "opt1")
           qmusic()
           pygame.display.flip()
       elif n == 16 and category == :
           qimg(sq16)
           button("A. 1", qbuttonposx, qbutton1ypos, qbuttonwidth, qbuttonheight, qblue, qblue, "opt2")
           button("B. 3", qbuttonposx, qbutton2ypos, qbuttonwidth, qbuttonheight, qblue, qblue, "opt1")
           button("C. 2", qbuttonposx, qbutton3ypos, qbuttonwidth, qbuttonheight, qblue, qblue, "opt1")
           qmusic()
           pygame.display.flip()
       elif n == 17 and category == :
           qimg(sq17)
           button("A. Sparta Rotterdam", qbuttonposx, qbutton1ypos, qbuttonwidth, qbuttonheight, qblue, qblue, "opt1")
           button("B. Excelsior", qbuttonposx, qbutton2ypos, qbuttonwidth, qbuttonheight, qblue, qblue, "opt1")
           button("C. Feyenoord", qbuttonposx, qbutton3ypos, qbuttonwidth, qbuttonheight, qblue, qblue, "opt2")
           qmusic()
           pygame.display.flip()
       elif n == 18 and category == :
           qimg(sq18)
           button("A. Alley-oop", qbuttonposx, qbutton1ypos, qbuttonwidth, qbuttonheight, qblue, qblue, "opt1")
           button("B. Dunk", qbuttonposx, qbutton2ypos, qbuttonwidth, qbuttonheight, qblue, qblue, "opt2")
           button("C. Smash", qbuttonposx, qbutton3ypos, qbuttonwidth, qbuttonheight, qblue, qblue, "opt1")
           qmusic()
           pygame.display.flip()
       elif n == 19 and category == :
           qimg(sq19)
           button("A. Eenpuntlijn", qbuttonposx, qbutton1ypos, qbuttonwidth, qbuttonheight, qblue, qblue, "opt1")
           button("B. Tweepuntslijn", qbuttonposx, qbutton2ypos, qbuttonwidth, qbuttonheight, qblue, qblue, "opt1")
           button("C. Driepuntslijn", qbuttonposx, qbutton3ypos, qbuttonwidth, qbuttonheight, qblue, qblue, "opt2")
           qmusic()
           pygame.display.flip()
       elif n == 20 and category == :
           qimg(sq20)
           button("A. Honkbal", qbuttonposx, qbutton1ypos, qbuttonwidth, qbuttonheight, qblue, qblue, "opt1")
           button("B. Softbal", qbuttonposx, qbutton2ypos, qbuttonwidth, qbuttonheight, qblue, qblue, "opt1")
           button("C. Voetbal", qbuttonposx, qbutton3ypos, qbuttonwidth, qbuttonheight, qblue, qblue, "opt2")
           qmusic()
           pygame.display.flip()
       elif n == 21 and category == :
           qimg(sq21)
           button("A. Pathe Schouwburgplein", qbuttonposx, qbutton1ypos, qbuttonwidth, qbuttonheight, qblue, qblue, "opt1")
           button("B. KFC", qbuttonposx, qbutton2ypos, qbuttonwidth, qbuttonheight, qblue, qblue, "opt1")
           button("C. Topsportcentrum Rotterdam", qbuttonposx, qbutton3ypos, qbuttonwidth, qbuttonheight, qblue, qblue, "opt2")
           qmusic()
           pygame.display.flip()
       elif n == 22 and category == :
           qimg(sq22)
           button("A. City Racing Rotterdam", qbuttonposx, qbutton1ypos, qbuttonwidth, qbuttonheight, qblue, qblue, "opt2")
           button("B. Rotterdam Racing through the City", qbuttonposx, qbutton2ypos, qbuttonwidth, qbuttonheight, qblue, qblue, "opt1")
           button("C. F1: Rotterdam", qbuttonposx, qbutton3ypos, qbuttonwidth, qbuttonheight, qblue, qblue, "opt1")
           qmusic()
           pygame.display.flip()
       elif n == 23 and category == :
           qimg(sq23)
           button("A. Dutch Basketball League", qbuttonposx, qbutton1ypos, qbuttonwidth, qbuttonheight, qblue, qblue, "opt2")
           button("B. NBA", qbuttonposx, qbutton2ypos, qbuttonwidth, qbuttonheight, qblue, qblue, "opt1")
           button("C. Basketball League A1", qbuttonposx, qbutton3ypos, qbuttonwidth, qbuttonheight, qblue, qblue, "opt1")
           qmusic()
           pygame.display.flip()
       elif n == 24 and category == :
           qimg(sq24)
           button("A. Trabzonspor", qbuttonposx, qbutton1ypos, qbuttonwidth, qbuttonheight, qblue, qblue, "opt1")
           button("B. Forward Lease Rotterdam", qbuttonposx, qbutton2ypos, qbuttonwidth, qbuttonheight, qblue, qblue, "opt2")
           button("C. Fenerbahce", qbuttonposx, qbutton3ypos, qbuttonwidth, qbuttonheight, qblue, qblue, "opt1")
           qmusic()
           pygame.display.flip()
       else:
           print("it no work mayne.")




def loop():
    while intro:
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                pygame.quit()
                quit()

        scherm.fill(white)
        clock.tick(30)
        imagesq()
        pygame.display.flip()

loop()